### ISSUE TITLE
Bug: Image selected from gallery is not shown on Android Emulator

### ISSUE THREAD

**Issue by mdolinin** [mdolinin/yapa#2]
Looks like path to image build in wrong way. Need too check.
Exception after selecting image from gallery.
```
════════ Exception caught by image resource service ════════════════════════════════════════════════
The following assertion was thrown resolving an image codec:
Unable to load asset: /data/user/0/com.example.yapa/app_flutter/image_picker4443190654015692374.jpg

When the exception was thrown, this was the stack: 
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
<asynchronous suspension>
#1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:664:31)
#2      AssetBundleImageProvider.load (package:flutter/src/painting/image_provider.dart:648:14)
#3      ImageProvider.resolveStreamForKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:501:13)
...
Image provider: AssetImage(bundle: null, name: "/data/user/0/com.example.yapa/app_flutter/image_picker4443190654015692374.jpg")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#87fe7(), name: "/data/user/0/com.example.yapa/app_flutter/image_picker4443190654015692374.jpg", scale: 1.0)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by mdolinin** [comment]
Root cause was using `AssetImage` to show files that stored in Application Documents Directory.
Looks like it works fine on iOS but fails on Android.
Need to use `FileImage(File('path to file')` instead it works fine on both platforms.
